import * as fs from 'fs';
import * as path from 'path';

async function consolidateSchemas() {
  const schemasDir = path.join(process.cwd(), 'supabase', 'schemas');
  const migrationsDir = path.join(process.cwd(), 'supabase', 'migrations');
  
  // Get all schema files in lexicographic order
  const allFiles = fs.readdirSync(schemasDir);
  const schemaFiles = allFiles
    .filter(file => file.endsWith('.sql'))
    .sort(); // Ensure lexicographic order
  
  console.log(`📄 ${schemaFiles.length} schema dosyası bulundu\n`);
  
  // Read and combine all schema files
  let combinedSQL = `-- Combined declarative schema migration
-- Generated from supabase/schemas/*.sql files
-- DO NOT EDIT THIS FILE MANUALLY - Regenerate using: npx tsx scripts/consolidate-schemas.ts

`;

  for (const file of schemaFiles) {
    const filePath = path.join(schemasDir, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    
    combinedSQL += `-- ============================================
-- File: ${file}
-- ============================================

${content}

`;
  }
  
  // Write to migrations directory
  const migrationFile = path.join(migrationsDir, '20251202000002_apply_declarative_schema.sql');
  fs.writeFileSync(migrationFile, combinedSQL);
  
  console.log(`✅ Schema dosyaları birleştirildi: ${migrationFile}`);
  console.log(`📊 Toplam ${schemaFiles.length} dosya birleştirildi\n`);
  
  return migrationFile;
}

consolidateSchemas().catch(console.error);

